name: BreakQuest
options:
  bundleIdPrefix: com.foculoom
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  createIntermediateGroups: true

settings:
  base:
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "20260226.1"
    SWIFT_VERSION: "6.0"
    TARGETED_DEVICE_FAMILY: "1,2"

targets:
  BreakQuest:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Sources/BreakQuest
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foculoom.breakquest
        PRODUCT_NAME: "Break Quest"
        PRODUCT_MODULE_NAME: BreakQuest
        INFOPLIST_FILE: Sources/BreakQuest/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: "RZWT5WST77"
        CODE_SIGN_STYLE: Automatic

  BreakQuestTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: Tests/BreakQuestTests
    dependencies:
      - target: BreakQuest
      - target: BreakQuestWatch
        embed: true
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foculoom.breakquest.tests
        DEVELOPMENT_TEAM: "RZWT5WST77"
        CODE_SIGN_STYLE: Automatic
        TEST_HOST: "$(BUILT_PRODUCTS_DIR)/Break Quest.app/Break Quest"
        BUNDLE_LOADER: "$(TEST_HOST)"


  BreakQuestWatch:
    type: application
    platform: watchOS
    deploymentTarget: "10.0"
    sources:
      - path: Sources/BreakQuestWatch
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.foculoom.breakquest.watchkitapp
        PRODUCT_NAME: "BQ"
        INFOPLIST_FILE: Sources/BreakQuestWatch/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        DEVELOPMENT_TEAM: "RZWT5WST77"
        CODE_SIGN_STYLE: Automatic
        SWIFT_VERSION: "6.0"
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "20260226.1"

schemes:
  BreakQuest:
    build:
      targets:
        BreakQuest: all
        BreakQuestTests: [test]
        BreakQuestWatch: all
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - name: BreakQuestTests
          randomExecutionOrder: true
      coverageTargets:
        - BreakQuest
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
